version: "3"
services:
  expert:
    container_name: expert_container
    image: node:12-buster
    working_dir: /usr/app/expert
    command: /bin/sh -c "make install-deps && npm run dev"
    environment:
      - PORT=8787
    volumes:
      - ./:/usr/app/expert/
    ports:
        - "8787:8787"