version: "3"
services:
  expert:
    container_name: expert_container
    image: node:12-buster
    working_dir: /usr/app/expert
    command: /bin/sh -c "make install-deps && npm run dev"
    volumes:
      - ./:/usr/app/expert/
    ports:
        - "8088:8088"
        - "8089:8089"